### ISSUE TITLE
WebUI Login Unauthorized while Logged in

### ISSUE THREAD

**Issue by asmoranomar** [ShokoAnime/ShokoServer-WebUI#110]
Version: Shoko Server 1.0.0.0 Web UI 0.3.3-dev4
Server Version: Shoko Server Mono Latest (as of 9/17/2017)
Browser: Chrome (latest) 64x

Problem:
Sometimes when restarting the Server while logged into the WebUI; when the session reconnects the WebUI will give an error and say "Unauthorized".  When attempting to login to the server using the same credentials, the server will allow the login, but will continue to give the "Unauthorized" error after login.

Workaround:
Logout and intentionally provide incorrect login information and receive the "Unauthorized" error at the login screen.  Proceed to login with the correct credentials fixes this error.

Other Issues:
The "Unauthorized" error covers the button needed to logout and refreshes quite frequently.   It was difficult figuring out where to locate the logout button the first time this occurred.

Steps to Reproduce:
1. Login to WebUI.
2. Restart Shoko Server.
3.  Check WebUI status when Shoko Server comes back online.  If the error occurs an "Unauthoirzed" error will appear in the upper right corner.  If the page is refreshed manually, you will still be "logged in" to WebUI, but all options will be reverted to their default settings and the error will remain.
4.  This error does not happen every time.

**Comment by hidden4003** [comment]
I think there were some changes to the token handling, before the tokens had no expiration so webui never bothered to obtain new one as it knew it will last forever.

**Comment by bigretromike** [comment]
Yeah, also is probably something similar to Cazzar problem that each time he auth he get new apikey.
Looks like this could have to do with it https://github.com/ShokoAnime/ShokoServer/commit/e85be6dfe939b0dbb6d7d36d036abd5ebfaa2167#diff-9695a309fda32e4abd36bb231c1c5630

**Comment by hidden4003** [comment]
Should logout automatically if it gets unauthorised response from server.
