### ISSUE TITLE
Interactive Log - reload each time I enter it

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#111]
Is it intended that after loading full log in  'Interactive Log' and switching dashboard and back to `Interactive Log' log is clear and need to be loaded again ?

Shoko Server 3.8.0.1024 Web UI 0.3.3-dev4

**Comment by ElementalCrisis** [comment]
Probably, as I recall the log was added but still needs to be worked on.

**Comment by hidden4003** [comment]
I didn't really think about it, in some cases you might want it to keep going from position that was last fetched it is still in memory, only way you loose it if you reload whole page, so I could make it continue. Currently it just resets on entering the tab.

**Comment by hidden4003** [comment]
I don't think the way it is currently done makes any sense tbh, I think much better implementation would be for server to give the list of log files, and by default it would load last 100 (adjustable) lines and a button to load the rest, or maybe just button to download the file itself.

**Comment by bigretromike** [comment]
looks like you deleted it ?
