### ISSUE TITLE
Separate CSS files

### ISSUE THREAD

**Issue by SuzuyaJuuzoudesu** [ShokoAnime/ShokoServer-WebUI#112]
Could you split the merged css into 2 parts, font awesome and bootstrap in one, the actual theme into another? This would allow easier customization and using ones own themes without them breaking if Shoko updates fa and bootstrap or spamming excessive !important into a second css file?

**Comment by ElementalCrisis** [comment]
Proper theming is probably one of the last things we'll add so don't expect this anytime soon. 

The current idea is to have a themes or skins folder with the theme/skin .CSS file which you can select from the settings window. The classes in there will take priority over the default classes so the user will only need to update the class color.
