### ISSUE TITLE
Bad binding issue - unable to add import folder.

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#119]
Cant tell if its Cazzar thing or webui, because im useing docker.
I mounted as /anime my import folder so the path is `/anime` inside container.
Webui see it and I pick it, give it a name and hit Add. no matter what I check with checkbox or not i get:
`Bad binding` and im unable to add folder

**Comment by joakimlemb** [comment]
@bigretromike and how did you fix this? I'm having the same issue.

https://xkcd.com/979/

**Comment by bigretromike** [comment]
@joakimlemb haha. If I did close it the same day I create it then It could have been some permission issue or something, cant tell for sure. I don't remamber also because ShokoAnime Support is redirected to Discord so no clues here. It was something on my (your) end or it was something simple that I overlooked. Can't be sure there.

**Comment by ElementalCrisis** [comment]
Any idea @hidden4003 or @Cazzar?

**Comment by hidden4003** [comment]
I don't really understand the issue. 

Docker build does not allow to map import folder? Correct ?

**Comment by bigretromike** [comment]
archangel543 from discord had similar issue, he resolve it by refreshing webui.

**Comment by hergonoway** [comment]
I've resolved the issue by switching back to 0.3.4

**Comment by PieQuest** [comment]
Any more info on this?
It's happening to me right now with a fresh install on UnRaid.

**Comment by hidden4003** [comment]
@PieQuest I need to know what versions of Shoko server and WebUI you are using.
