### ISSUE TITLE
Wizard in 0.3.3 dont work with Cazzar docker.

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#120]
After clean install and first enter the webui there was no wizard presented. 
Without any button to execute wizard in this condition its unable to do anything with shokoserver from docker.

**Comment by hidden4003** [comment]
It works, if you manage to refresh exactly when host it up but db is not created you will see it.
Linux has automatic creation of sqlite database so it is not my bug.

**Comment by bigretromike** [comment]
Ok that's make sense 

On February 21, 2018 8:33:36 PM GMT+01:00, hidden4003 <notifications@github.com> wrote:
>Closed #120.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer-WebUI/issues/120#event-1485453287

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
