### ISSUE TITLE
Error with creating ssl/tls secure channel

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#139]
shokoserver: 3.9.0.1029
WebUI: 0.3.4

After login in I see red error:
```
Error  
Network error: /webui/latest/ 500: The request was aborted: Could not create SSL/TLS secure channel.
```

The error display again when I log back - but only once.

**Comment by ElementalCrisis** [comment]
I didn't know we supported SSL/TLS yet. Any idea @hidden4003?

**Comment by bigretromike** [comment]
because we probably ain't . it looks like github version check

**Comment by hidden4003** [comment]
Looks like it is coming from the server nor a webui problem.

**Comment by bigretromike** [comment]
I added it to server : https://github.com/ShokoAnime/ShokoServer/issues/749
