### ISSUE TITLE
cookie support or other session manager

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#140]
WebUI dont store sessions
Each time you enter you need to login

**Comment by ElementalCrisis** [comment]
Something that can be added to make things easier.

**Comment by hidden4003** [comment]
webui uses session storage which allows you to refresh page, but as soon as you close browser it is deleted

**Comment by bigretromike** [comment]
hmm... I will check it later today, if you say it is there maybe some plugin cleared it or something.

**Comment by hidden4003** [comment]
I am not sure but it seems to be we do not understand each other.

What webui has is sessionStorage, can be seen here: https://github.com/ShokoAnime/ShokoServer-WebUI/blob/841aec84e58f60096ab50e42190e11776713afe0/src/core/localStorage.js#L5-L15

You can read more about sessionStorage here: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

Important part is: 
> A page session lasts for as long as the **browser is open** and survives over page reloads and restores.

**Comment by bigretromike** [comment]
I think I understand it but I recall that I refresh browser and it end up on login screen. 

But it looks its ok now. Probably something on my end, because it work as you describe on other machine.
