### ISSUE TITLE
Action Tab

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#141]
Should it work, because I cannot enter it the mouse don't change while I hover over it.

**Comment by ElementalCrisis** [comment]
No, it hasn't been created yet and I don't believe all the actions have API endpoint yet.

**Comment by bigretromike** [comment]
not all api endpoint are for setting but we got them

**Comment by hidden4003** [comment]
Should work now in 0.3.5-dev3 bu you need https://github.com/ShokoAnime/ShokoServer/commit/01da388b5a96d3cdf817dd946beebfca48b67ba5 for it to save the dashboard actions.
