### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#142]
Its something small as this but still needed.
Can we change favicon from Nancy to anything else (probably shokoserver icon for now)

**Comment by ElementalCrisis** [comment]
I did this locally but never pushed the changes, I'll get this done soon.

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer-WebUI/pull/144#issuecomment-405174883
