### ISSUE TITLE
White login screen with spinning wheel

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#170]
`3.9.5.12601(WebUI 0.3.5-dev8)`

After updating from stable to unstable.

![zas](https://user-images.githubusercontent.com/6052025/64670146-576ba000-d464-11e9-98bd-7c355c9d09b4.png)

`http://127.0.0.1:8111/api/v2/image/7/random` return empty image;

**Comment by bigretromike** [comment]
This is because I have empty database - aka `first time experience` the server return proper 404 http code, so please check for that and use default background if there is 404;

**Comment by ElementalCrisis** [comment]
Interesting, there's a default image that's supposed to be used. @hidden4003 can you take a look?

**Comment by bigretromike** [comment]
yes, there is - but it get overwriten by null image from random (with http code 404)

**Comment by hidden4003** [comment]
I am assuming you have no series and no images in the server.

That is a server issue tho if server returns a valid image then webui is unable to switch to fallback image, we can't really analyze image clientside, server is not supposed to return blank image if it has none. Previous versions did 404 or 500 at it used default as expected.

**Comment by bigretromike** [comment]
I have series, but no images from tv, so no image would get return on random.
I dont know what had changed because I didn't touch it ;-) but I recall seeing 404 with null image.
You could analyze image by size , if its lower than 10KB it can't be anything good. that way you protect used from low quality image :-)

**Comment by hidden4003** [comment]
This is the literal code doing the image, https://github.com/ShokoAnime/ShokoServer-WebUI/blob/7e6cddcce8b816a5fa02b9cd746ed61550ecefe0/css/login.scss#L2 please do tell me how can I do this in CSS? I can do the whole thing with fetching image from server trying to parse it then replace in js but if simple solution worked before then maybe it is not a webui issue :)

**Comment by bigretromike** [comment]
so if you telling me that this did worked, then this is probably another thing that apiv3 implementation broke :(
