### ISSUE TITLE
Update webui is broken

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#171]
endpoint on server are working fine:
`/api/webui/update/stable` and `/api/webui/update/unstable`

Im unable to force webui to update, there is no button it does not look for it after some time.

yet, im fine doing update via cli/curl/api with no issue;

**Comment by bigretromike** [comment]
Also, while using latest, it shows that there is update and after clicking it gives
`Network error: /webui/update/ 404: Not Found`
Which is correct because there is no such api endpoint.

**Comment by bigretromike** [comment]
this button does work when you got to settings and set proper channel to update;

**Comment by hidden4003** [comment]
Should be fixed, reopen if it appears again.
