### ISSUE TITLE
[req] Ability to scan per folder

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#180]
In GUI you can click yellow folder next to Import folder to rescan only that folder. 
And I'm more than sure there is endpoint in v2 for that.
Any chance to adding that ?

**Comment by hidden4003** [comment]
API issue, will fix itself when server is fixed https://github.com/ShokoAnime/ShokoServer/issues/819

**Comment by harshithmohan** [comment]
Added in the WebUI 1.0 (#194)
