### ISSUE TITLE
[req] Information about ban

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#181]
In GUI you can see (only 1 ?) information about you being banned ex. AniDB(HTTP). It would be cool to see that information in webui, because that information is missing if you use console version (and dont have access to log/or dont want to access them)

**Comment by ElementalCrisis** [comment]
@harshithmohan this is done right?

**Comment by harshithmohan** [comment]
Yes, it's done, in v2
