### ISSUE TITLE
Add Import Folder Type & Status

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#19]
![dashboard - import folders](https://cloud.githubusercontent.com/assets/9443295/17618335/f6a36a7a-6033-11e6-9649-39713001b0ae.png)

Refer to mockup above, makes the box seem less empty.

**Comment by bigretromike** [comment]
@ElementalCrisis if this is a 0.2.0 milestone, please update roadmap

**Comment by ElementalCrisis** [comment]
Oh your right it is, forgot I already added it.

**Comment by hidden4003** [comment]
Not a core change as there is no "Core" yet strictly speaking :)

**Comment by hidden4003** [comment]
What do online/offline mean ? There is no option to disable/enable an import folder.

**Comment by bigretromike** [comment]
hes probably remaking jmmd inside webui. online = accessible? or if cloud is on mind, same = accessible ?

**Comment by maxpiva** [comment]
Remember cloud support if possible. 
![fld2](https://cloud.githubusercontent.com/assets/1164141/17636763/b79d21ae-60b5-11e6-91d6-b5f064c58210.png)
![fld1](https://cloud.githubusercontent.com/assets/1164141/17636762/b79c62f0-60b5-11e6-92b0-f4b8673c609d.png)

**Comment by ElementalCrisis** [comment]
Good call @maxpiva, I'm thinking it should go number, type, location, provider and then status. Should fill the box up nicely.

**Comment by bigretromike** [comment]
Remamber that cloud is not in nancy repo :-) if someone will rebase it then sure. 

On August 12, 2016 11:08:58 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>Good call @maxpiva, I'm thinking it should go number, type, location,
>provider and then status. Should fill the box up nicely.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver-webui/issues/19#issuecomment-239560237

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
Well we can still add it as a placeholder.

**Comment by hidden4003** [comment]
Rebase is not possible, branches are too far apartI. I tried it too many conflicts, so merge is the only possibility .
