### ISSUE TITLE
check api version before showing login screen

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#2]
/api/version - check { api: int } for compatibility if api is same of lower than supported version then pass thru if not show update button

Do we need user to auth to update webui or we pass him without login/pass ?

**Comment by bigretromike** [comment]
Auth user is needed as it would be security law.
Let him login and then check version so you know if you can show any menu elements instead of "Update now"

**Comment by bigretromike** [comment]
@hidden4003 wasn't this added to check version of server

**Comment by hidden4003** [comment]
I only use it to show server version on login screen, the actual API version is not checked, and if update without login is insecure then only thing I can do is show some sort of message with instructions on how to download release from github and manually install it.

**Comment by bigretromike** [comment]
why? you could add to that message same action as for button to update to newest version or instead of message dialogbox or button.
or log in normalny but from top there would be a big notice bar with information to update.

It most cases old webui will work with newer jmmserver and that should not be the problem.
The only big problem would be using latest webui with older jmm.
so:
```
if jmm.api > webui.require then message/dialog for sugestion of updating webui as you lack of new features but webui is accessible
if jmm.api < webui.require then maybe lower webui option ? (lastest known for this api version) or message that webui wont work with this low version and you should update to latest stable or switch to stable webui channel 
```

What do you think about it ?

**Comment by hidden4003** [comment]
sure but it will mean we can't change how authentication works? because you need to get token before you can call update API

**Comment by bigretromike** [comment]
yes. that is correct, because if you had server on wan someone could reinstall your webui without token - which is not something we would like. Right?!

You need to login before updating.
Login -------------> login,pass
apikey <-------------  server
if(Login.Success) then { if (CheckApiCompatibilte()) { DrawMenu()} else { MessageAboutIt() } }

**Comment by hidden4003** [comment]
This will be irrelevant in netcore since it has api versioning server-side so clients can choose which one they support.
