### ISSUE TITLE
Unknown Action when running AVDump Mismatched Files

### ISSUE THREAD

**Issue by NTWarrior** [ShokoAnime/ShokoServer-WebUI#208]
Version: 1.0.1-dev1

In the webui I get "Unknown Action" when I try to run the bulk Avdump mismatched files option, and when I click to Avdump a single file there's no error but nothing seems to happen - the General count in commands doesn't go up. It looks like the Avdump package isn't being downloaded either.
The server logs don't show anything related to Avdump or "Unknown Action".

**Comment by harshithmohan** [comment]
I fixed the "Unknown Action" error in #210.
Also, that is not exactly a bulk avdump action. It avdumps whatever files which are *not* on anidb and doesn't show any ed2k hashes. Currently, we don't have a "bulk" avdump unrecognized files option.

About avdump not working entirely. Which server version are you using and are you using it on docker?

**Comment by NTWarrior** [comment]
4.0.0, Windows without Docker

**Comment by harshithmohan** [comment]
Try avdump from the desktop too, if it doesn't work then it's a problem with the server. Also, can you come to our discord server, if you can? Discussions are more convenient there.

**Comment by NTWarrior** [comment]
Avdump still works from Shoko Desktop. I actually reported this first on Discord but Elemental Crisis asked me to log the issue here instead!

**Comment by harshithmohan** [comment]
Sorry, I must've missed your message.
Anyways, I'll need logs.
Avdump some file from the webui, and then post the server logs here.

**Comment by da3dsoul** [comment]
Regardless of whether that button works, chances are that you shouldn't be clicking it

**Comment by harshithmohan** [comment]
Stale issue, closing.
