### ISSUE TITLE
Unrecognized Tab Showing Zero Entries

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#209]
Might be an issue with the API but as you can see, I have 38 unrecognized files but the unrecognized tab shows zero. 

Shoko Version: 4.0.0
Web UI Version: 1.0.0

![image](https://user-images.githubusercontent.com/9443295/90977562-34ae8c00-e4fb-11ea-970b-f7f6e97aaada.png)

**Comment by harshithmohan** [comment]
Fixed in #207
