### ISSUE TITLE
Same time and date for all entries in import breakdown

### ISSUE THREAD

**Issue by ablakers** [ShokoAnime/ShokoServer-WebUI#211]
Everything I have seen in my import breakdown so far has a timestamp of 2020-08-22 / 07:24 PM, which might have been when I began the import on this fresh install. This has persisted from 1.0.0 to 1.0.1-dev2 so far. My server's running on W10 2004.

**Comment by harshithmohan** [comment]
AFAIK, the server stores the "created" time as the time when it first found the files. @da3dsoul can you confirm?
The WebUI just shows whatever time is returned by server.

**Comment by da3dsoul** [comment]
Correct

**Comment by harshithmohan** [comment]
Closing this as it's not an issue. This is how the system is intended to work.
