### ISSUE TITLE
Additional Settings That Need To Be Added

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#214]
As these are global settings, we need to add them to the Web UI Settings page. 

- [ ] Language Settings
- [ ] Relation Settings
- [ ] Import Settings
- [ ] Plex Host & Library Linking

Relation
![image](https://user-images.githubusercontent.com/9443295/91680735-09cac600-eb01-11ea-9fa5-c4e01e481b7a.png)

Language 
![image](https://user-images.githubusercontent.com/9443295/91680720-fe779a80-eb00-11ea-803f-ba34540b7d93.png)

Import
![image](https://user-images.githubusercontent.com/9443295/91680823-5f06d780-eb01-11ea-91d0-1b97bd4de427.png)

**Comment by ElementalCrisis** [comment]
Plex Host & Library Linking
![image](https://user-images.githubusercontent.com/9443295/93010126-c9763980-f53d-11ea-8951-5cab68cc4483.png)

**Comment by xmodx10** [comment]
Please add the new import exclusion setting to the list :)

**Comment by ElementalCrisis** [comment]
@xmodx10 can you screenshot it for us please.

**Comment by harshithmohan** [comment]
He means this. In `settings-server.json`
![Screenshot_2020-09-27_20-23](https://user-images.githubusercontent.com/26010946/94367956-52c16a80-00ff-11eb-81ac-00128fc05e6f.png)

**Comment by ElementalCrisis** [comment]
Ah, that should be added in the Import Settings then, maybe below the include list?

**Comment by harshithmohan** [comment]
Do you mean the "Import Folders" panel?
It works like `.plexignore`. It's not something that you do on the daily. It's just "set and forget". I think it should be in the settings.

**Comment by Cazzar** [comment]
Having people able to update it would be useful, as to do the JSON you need to account for JSON escaping, for example, the first one is actually: `[\\\/\]$RECYCLE\.BIN[\\\/\]`.
If you wanted to get extra fancy, you could even do regex highlighting on adding new entries.

**Comment by xmodx10** [comment]
I think @ElementalCrisis is refering to the "import settings" area/screenshot that he referenced in his first post. That it should be put under the "Video extension" list (include list) when it gets implemented into the webui
