### ISSUE TITLE
Missing settings in Web UI like Picture folder location / tracelog

### ISSUE THREAD

**Issue by titisouven** [ShokoAnime/ShokoServer-WebUI#222]
There currently isn't a way to set the Image Path to another location in the web UI.
Shoko Desktop still has the "Image Path" setting under Essential, but it has no effect.

The json file has a setting "TraceLog": true,
This can't be set via the Web UI but is often needed to communicate additional data in the support channel.
It's practical to get assistance.

**Comment by ElementalCrisis** [comment]
Closing, added to #417.
