### ISSUE TITLE
Web UI Delete Action not reading value from Json file

### ISSUE THREAD

**Issue by titisouven** [ShokoAnime/ShokoServer-WebUI#223]
A previous bug report solved an issue in release 1.1.0-dev3.
The issue was that Delete action was affecting storage in json
And Storage in the Web Ui was changing the delete action value in json.

There is however still an issue with the Delete action combo box.
The json is updated correctly, but upon refreshing the page, or going back to the web settings after a couple seconds, the Delete Action value will show "Delete File (Local).

The json will still be set on the correct value (ex. MarkDeleted) and chaning the combo box value will update correctly the json, but the json's value is not loaded back as the selected combo box value for Delete Action in the Web UI.

**Comment by titisouven** [comment]
It was a cache/local storage issue in firefox.
Deleting the local storage in the dev tools (F12) under the storage tab resolved the issue.

**Comment by harshithmohan** [comment]
The problem has been solved, closing the issue.

**Comment by titisouven** [comment]
Thanks. Does this mean the next dev release will have versioning on the storage elements to avoid caching issues (as discussed on discord support)? Or did you close it because I mentioned a fix?

**Comment by harshithmohan** [comment]
Both
