### ISSUE TITLE
Old log being added to current log when WebUI opened/reloaded.

### ISSUE THREAD

**Issue by Malific** [ShokoAnime/ShokoServer-WebUI#229]
Issue requested by Elemental Crisis
1) WebUI opens to Log instead of Dashboard.
2) Very old log (assumed from server first time run) is added after current log loads when WebUI is opened.
As seen here: https://discord.com/channels/96234011612958720/96235819366371328/806219252092370986

**Comment by hidden4003** [comment]
The opening wrong tab should be fixable here but the bad log comes from server.

**Comment by hidden4003** [comment]
fixed in 1.1.5
