### ISSUE TITLE
switching between channels and updating don't save channel status

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#256]
I used 1.1.0 (stable),
I switched to `unstable` checked for newest version, one one found
I clicked install icon next to version
webui notificate me it will log me off
I log back
On setting screen I had channel switched to `stable` and because of it the update icon was there again (for stable version)
I switch back to `unstable` channel and webui saved that

**Comment by harshithmohan** [comment]
Fixed in latest dev release
