### ISSUE TITLE
TypeError: item.Locations is undefined

### ISSUE THREAD

**Issue by Grenaid** [ShokoAnime/ShokoServer-WebUI#258]
Tried reinstalling latest, tried running the daily.  This is the only thing I can get to show in the webUI.  Started when I was running a scan of some sort after not running for a while.
```
ERROR

You broke the Web UI, congratulations.

Hopefully useful information:

TypeError: item.Locations is undefined

Trace:


    in ImportedTab
    in ConnectFunction
    in div
    in div
    in FixedPanel
    in ImportBreakdown
    in ConnectFunction
    in div
    in Resizable
    in DraggableCore
    in GridItem
    in div
    in ReactGridLayout
    in ResponsiveReactGridLayout
    in WidthProvider
    in DashboardTab
    in ConnectFunction
    in div
    in div
    in div
    in MainPage
    in ConnectFunction
    in Route
    in AuthenticatedRoute
    in ConnectFunction
    in Switch
    in Router
    in ConnectedRouter
    in ConnectedRouterWithContext
    in ConnectFunction
    in div
    in Unknown
    in ConnectFunction
    in ErrorBoundary
    in components_Provider
    in app

Go back, or head over to the home page to choose a new direction.
```
Going "back" or to the home page is not possible, there's no frame or anything to click on.

**Comment by bigretromike** [comment]
Try refreshing F5 page. if thats not a thing, close shokoserver and restart it. Should do the trick (did for me)

**Comment by Grenaid** [comment]
> 
> 
> Try refreshing F5 page. if thats not a thing, close shokoserver and restart it. Should do the trick (did for me)

Nah tried all that.  As I said, I reinstalled the server.

**Comment by bigretromike** [comment]
@Grenaid did you try to install webui manually ?

**Comment by Grenaid** [comment]
Can you elaborate? I never installed anything other than shoko server and shoko desktop.

**Comment by bigretromike** [comment]
@Grenaid 
download https://github.com/ShokoAnime/ShokoServer-WebUI/archive/refs/tags/1.1.1-dev7.zip
unzip the content of folder into shokoserver install location into `webui` folder

**Comment by Grenaid** [comment]
Assuming this is the folder:

<img width="244" alt="shoko" src="https://user-images.githubusercontent.com/441380/141202567-69e3bc3b-9fa4-450e-be30-9c4a50e6d4f1.png">

This is it after dump:

![image](https://user-images.githubusercontent.com/441380/141202651-a1eb44f1-eb7e-4fd9-82bc-096e1308f3d5.png)

Same issue.

Oddly I do get a different screen when in private:

![image](https://user-images.githubusercontent.com/441380/141202721-2d0858d7-6481-4939-9a21-443d6e081e4e.png)

**Comment by bigretromike** [comment]
glad you got it resolved.
