### ISSUE TITLE
Error starting up ShokoDesktop

### ISSUE THREAD

**Issue by rebyul** [ShokoAnime/ShokoServer-WebUI#259]
Gettings a null reference exception when starting up ShokoDesktop.
I've tried a reinstall of shoko desktop, but it doesn't seem to resolve the issue.
Shoko server seems to be running fine.
Shoko Desktop: v4.1.1
Shoko Server: v4.1.1

![image](https://user-images.githubusercontent.com/2460325/146642278-9144126e-3107-4b09-93b5-268a954f01f2.png)

**Comment by da3dsoul** [comment]
C:\ProgramData\ShokoDesktop
Delete the settings file in there.

**Comment by rebyul** [comment]
Sorry I've formatted my computer since so I can't confirm whether your solution fixes the issue. You may close this ticket thank you.
