### ISSUE TITLE
Import Folders tab

### ISSUE THREAD

**Issue by hidden4003** [ShokoAnime/ShokoServer-WebUI#35]
![import folders tab](https://cloud.githubusercontent.com/assets/197087/17692906/0362e73a-63a5-11e6-8941-0cbf117cacc1.png)
We are reusing top section and folders overview from main page, the new thing is series files in a folder.
- [x] Make new tab and connect to sidebar
- [x] API call to get series file list by import folder id (@bigretromike)
- [x] Connect it to UI

**Comment by bigretromike** [comment]
so you want to list all series inside "import FoldeR"
do you want all files also or uinrecognized only for that folder ?

**Comment by hidden4003** [comment]
It does not show actual files but it collects folders, sizes and counts the files. So obviously it can't show unrecognized as they can't be associated with a series.

**Comment by bigretromike** [comment]
there is no relation between series and import folders inside database of current 3.6.
the only relationship that could be used it importfolder <-> file.
I could iterate each file to match correspond series but do we want series or files

**Comment by bigretromike** [comment]
I added /api/serie/byfolder/{int} sadly I couldnt come out with better name ;-)

**Comment by bigretromike** [comment]
I will add a limiter to it also as you probably dont want to lock up webui;-)

**Comment by bigretromike** [comment]
/api/serie/byfolder/{int} - give you 10 series from ImportFolder id
/api/serie/byfolder/{int}/{max} - give you MAX series from ImportFolder id

**Comment by hidden4003** [comment]
I added the tab into 0.1.10-dev2. 
For left pane what is needed is to get an import folder status, i.e. is it accessible to jmm server or not, but @bigretromike said he can't change contracts, so don't know if possible until we merge nancy and cloud.

**Comment by hidden4003** [comment]
@bigretromike it should be /api/import/{folder_id}/series/{int}
The only link there is you take the files and remove the filenames, then you add it to list, if folder exists in list you don't add it, after that you take the series for the file and add to another list.
You should have 2 lists:
1 - Series, File count, File size
2 - Directory, Series ID

So if series is spread out over several folders I will show it like: 
Anime Name | Folder1, Folder2 | 235 files | 1.5 Gb

**Comment by bigretromike** [comment]
aint it postprocessing - maybe other will use it to make other graphic representations...
why not make it on webui side this time ? in this rate will will have 1 set of calls to get full data and 1 set to have them slutter and compress ;-) 
If you like to please update it to resolve your needings - im done for today 🍻

**Comment by hidden4003** [comment]
I tried to do it in the UI, but it is currently impossible, I can't get episode list from a series and I can't get to files, so I can't determine the files that are related to series.

**Comment by hidden4003** [comment]
I looked into the code of existing command and it was finding the series by enumerating all the files so I made separate command to count some stats instead of returning series list.

**Comment by bigretromike** [comment]
good job

**Comment by bigretromike** [comment]
What is missing from this ?

**Comment by ElementalCrisis** [comment]
Cloud support I believe and I think managing imports folders and adding new one does not work.
