### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#4]
Remember about wizard 
and remember about checking api version also somewhere between

**Comment by ElementalCrisis** [comment]
![initial setup - step 1](https://cloud.githubusercontent.com/assets/9443295/19466010/0133c332-94bd-11e6-96ce-06f1ae123d5f.png)
![initial setup - step 1 - invalid](https://cloud.githubusercontent.com/assets/9443295/19466008/01312b36-94bd-11e6-8eab-6d0886a6a65c.png)
![initial setup - step 2](https://cloud.githubusercontent.com/assets/9443295/19466007/0130b246-94bd-11e6-9ae4-373b00f200d5.png)
![initial setup - step 3](https://cloud.githubusercontent.com/assets/9443295/19466009/01326794-94bd-11e6-85d2-ed23568012e8.png)
![initial setup - step 4](https://cloud.githubusercontent.com/assets/9443295/19466011/0138394e-94bd-11e6-92cb-0a7d5f23cda4.png)
![initial setup - step 5](https://cloud.githubusercontent.com/assets/9443295/19466012/0139205c-94bd-11e6-899c-b80874b568bc.png)

**Comment by ElementalCrisis** [comment]
While we keep the instruction part, what about using a navigation style similar to this?
http://bootsnipp.com/snippets/featured/content-in-bootstrap-tabs

**Comment by bigretromike** [comment]
if you cut out most of the upper text from mockup then yes. other wise it would be the same (with exception of icons)

**Comment by ElementalCrisis** [comment]
It would go the icon navigation, info box and then tab settings.

**Comment by ElementalCrisis** [comment]
Hey @bigretromike, can we get DB related settings such as initializing DB and creating users added so @hidden4003 can start working on the wizard?

**Comment by bigretromike** [comment]
they should be there. you ask because they are missing/not_working, or because you want to push this and not sure if this is there ?

**Comment by ElementalCrisis** [comment]
Just relaying a message, @hidden4003 should know more.

**Comment by bigretromike** [comment]
From what I read this is done, right

**Comment by hidden4003** [comment]
Closing, we need new one with new mockup for 0.3.6
