### ISSUE TITLE
Baines findings

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer-WebUI#421]
As requested by EC, here's what I've found/noticed so far:

(all in unrecognized utility)
manually linked 3 files, all good
selected 8 files, manual link
only 3 entries available on either side
reloaded the page, reselected the 8 files, manual link
selected the show, pressed fetch data.
episodes only shown after pressing cancel and pressing manual link again
left pane is scrollable, has the entries selected. right pane is fixed, only 6 "select episode"
linking more than 6  would currently require doing batches of 6 files
range start/fill not implemented yet

**Comment by hidden4003** [comment]
@Baine things regarding refresh and selected files/series not resetting should be fixed. I forced left side to 1 line only so it should always align properly with right side.

range start/fill not implemented yet

**Comment by Baine** [comment]
When doing a manual link with multiple files, the pane on the left (which holds the files) is reordered after selecting the episodes on the right pane.
Order Before selecting episodes:
1
2
3
4

Order after selecting episodes:
2
3
1
4

**Comment by hidden4003** [comment]
Everything here should be fixed now
