### ISSUE TITLE
Unrecognized Files - File to Episode assignment scrambled

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoServer-WebUI#453]
while the list of files is sorted alphabetically (i think?) and the episodes on the right are fixed to the file entry (while scrolling etc),
the file to episode assignments are scrambled when saving those links.

while testing file with episode 02 was linked to the anidb episode 09

**Comment by hidden4003** [comment]
episode select is linked to file id so it means selects are not sorted same as files, did you by chance had 10 files ? i.e. can it be that order is reversed ?

**Comment by Baine** [comment]
there were actually 12 files
and the file 2 was aligned with episode 9 as well before you made the sorting changes
