### ISSUE TITLE
Files Count Only Updates When Tab Switching

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#47]
The Files count only updates when you switch the tab, staying on the Dashboard tab for example will not update the files count even after all commands have been processed.

**Comment by hidden4003** [comment]
it shouldn't update even with tab switch as it is not hooked to auto update

**Comment by bigretromike** [comment]
maybe browser issue then?

**Comment by hidden4003** [comment]
Somewhat fixed in 0.3.2-dev2 overview part was only updated on dashboard, now it will request api on every tab switch.

Regarding the file count update it seems wasteful to request overview every xx seconds for a slim chance file count might've changed. Should we leave it as is?

**Comment by hidden4003** [comment]
Waiting for websockets to really solve this.

**Comment by hidden4003** [comment]
With SignalR that should be fixed.
