### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#52]
with infomation and setting about current loged user.
change password
maybe mal/anidb related things ? dunno

**Comment by ElementalCrisis** [comment]
Alright here's v1 of the user profile.

![user profile v1](https://cloud.githubusercontent.com/assets/9443295/18582115/641ca752-7bb8-11e6-88df-0cd29b2fe191.png)

We can use the user profile to store user specific information like usernames/password for community sites and AniDB. This way we can have the generic fields like AniDB port for example in the settings panel and just display the info from the user profile.

The image for last watched and last rated are series banners from TvDB, we can resize them to the appropriate size and provide a generic wide banner if the user does not download wide banners or the series does not have one.

**Comment by bigretromike** [comment]
remamber this is webui-server :-) so we dont end up making it client (I wouldn't mind to be honest) 👍 
Next logic thing would be add play button on latest shows ;-) 
So if you really dont want to make it client like ;-) (till later) I would wipe those right colums and stick to left one
