### ISSUE TITLE
Quick multi selection - Shift Click

### ISSUE THREAD

**Issue by ItzzLincler** [ShokoAnime/ShokoServer-WebUI#531]
Just a quality of life thing:
Allow quick multi selection of list items with a shift click.

**Comment by revam** [comment]
It's on the list of improvements already.

**Comment by danielbr14** [comment]
Oh, good to know.
I tried looking for one but I couldn't find one, is it publicly available?

**Comment by revam** [comment]
We can use this issue to track it. Previously it has only been stored in people's memory.

**Comment by harshithmohan** [comment]
Fixed in #538
