### ISSUE TITLE
0.3.0-dev issues

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer-WebUI#68]
- [x] "update available" showing, but clicking it don't do anything 
- [x] quick actions - some of them are in API but not there
- [x] change password don't work
- [x] import folder - manage don't work
- [x] setting/log - throw 404 when I click "manage" on import folder before going there
- [x] logout don't work - should redirect to /webui/
- [x] update /api/config

**Comment by hidden4003** [comment]
Import and logs fixed in https://github.com/japanesemediamanager/jmmserver-webui/commit/2c2dc93cd322ea13896ad47e36e20f7327419bbf

**Comment by bigretromike** [comment]
Old settings was moved to /config/ please update webui if it use it: https://github.com/japanesemediamanager/jmmserver/commit/384dd9249212d3bfb54f01ff7e5807a31b5073c2

**Comment by hidden4003** [comment]
Logout and /api/config are fixed in https://github.com/japanesemediamanager/ShokoServer-WebUI/commit/4f3ddd87327ef98b27792604059a8e5ad853c314

**Comment by bigretromike** [comment]
api for changing password was working last time I checked; any problem with it ?

**Comment by bigretromike** [comment]
its 0.3.4 so we are over this one.

**Comment by hidden4003** [comment]
I was keeping the password change as an easy task for first time contributors, but I guess I will have to fix it.

**Comment by bigretromike** [comment]
@hidden4003 password change still dont work in 0.3.5-dev2
