### ISSUE TITLE
Settings That Need To Be Added

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#70]
This is just a general list so we know what needs to be added. As discussed a lot of settings from Desktop will be added so if unclear check the desktop settings section. 

We should also work on improving the settings and not just copying them over.

**Web UI Settings**
- Light/Dark
- Custom
- Turn Off Notifications

**Log Rotator**
- On/Off
- Schedule (X Days, Daily, Weekly, Monthly)
- Zip (Yes/No)
- Delete (Yes/No)

---

~~~**DB Settings**~~~ (not happening on this screen and this issue)
~~~- Type~~~
~~~- Port~~~
~~~- Server Address~~~
~~~- Database Name~~~
~~~- Username~~~
~~~- Password~~~

---

**Windows Only Settings**
- Start With Windows
- Minimize To Tray
- Start Minimized

---

~~~**AniDB Login Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/130)
- ~~~Username~~~
- ~~~Password~~~
- ~~~Port~~~
- ~~~AvDump Key~~~
- ~~~AvDump Port~~~

~~~**AniDB Image Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/131)
- ~~~Download AniDB Poster~~~ (no setting, and also makes no sense)
- ~~~Download Character Images~~~
- ~~~Download Creator Images~~~
- ~~~Creator images~~~ (added)
- ~~~Release group~~~ (added)

~~~**AniDB MyList Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/131)
- ~~~Add Files~~~
- ~~~Storage State Options~~~
- ~~~Delete Action Options~~~
- ~~~Mylist Sync Options~~~
- ~~~Local Sync Options~~~

~~~**AniDB Updates**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/131)
- ~~~Update MyList Every X (6/12/24 Hours, Week, Month)~~~
- ~~~Get MyList Stats Every X (6/12/24 Hours, Week, Month)~~~
- ~~~Update Anime and Episode Info Every X (6/12/24 Hours, Week, Month)~~~
- ~~~Update Files With Missing Info Every X (6/12/24 Hours, Week, Month)~~~

---

~~~**TvDB Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/135)
- ~~~Download Fanart~~~
- ~~~Download Wide Banners~~~
- ~~~Download Posters~~~
- ~~~Max Fanart~~~
- ~~~Max Wide Banners~~~
- ~~~Max Posters~~~
- ~~~Update Data Every X (6/12/24 Hours, Week, Month)~~~
- ~~~TvDB Language~~~

---

~~~**MAL Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/136)
- ~~~Username~~~
- ~~~Password~~~
- ~~~Sync Watched States (Yes/No checkbox)~~~
- ~~~Sync Ratings (Yes/No checkbox)~~~ (not a separate setting)
- ~~~Never Decrease Series Status~~~

---

~~~**Trakt Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/136)
- ~~~Trakt PIN~~~ (new auth is used PIN is deprecated)
- ~~~Update Data Every X (6/12/24 Hours, Week, Month)~~~

---

~~~**Movie DB Settings**~~~ (Done https://github.com/ShokoAnime/ShokoServer-WebUI/pull/136)
- ~~~Download Fanart~~~
- ~~~Download Posters~~~
- ~~~Max Fanart~~~
- ~~~Max Posters~~~

---

**Preferred Language Settings**
- See JMM Desktop

---

**Relation Settings**
- See JMM Desktop

---

**Web Cache**
- See JMM Desktop

**Comment by ElementalCrisis** [comment]
@bigretromike I know most of these settings are in Server but have they been added to the API?

**Comment by bigretromike** [comment]
I'm thinking that its future proof - but I will check it, in few minutes and tell you.

**Comment by bigretromike** [comment]
API use model from here: https://github.com/japanesemediamanager/Shoko.Models/blob/3eb5e5c5b18b81a404b922d58c3c9895e9129f2b/Client/CL_ServerSettings.cs  Anything there is supported by API.

**Comment by hidden4003** [comment]
@ElementalCrisis @bigretromike  I was told by da3dsoul that changing db settings in a running server is a legacy thing and is a very bad thing in general so I don't think we will be adding that here. 

Even if we do add it, it will probably be some Troubleshooting/Maintenance page.

**Comment by bigretromike** [comment]
changing idk, there need to be setting to enable wizard then something like `FirstRun = True`. 
Or changing setting would need to restart shoko server, there need to be way to change db settings somehow imo, somehow via wizard or by Troubleshooting/Maintenance page; Maybe it should store those information and re-run shoko so those setting take effect only then ? dunno.

**Comment by ElementalCrisis** [comment]
Users will not be able to select MySQL or SQL Server during setup. You'll only see first run if it's never been run before.

**Comment by bigretromike** [comment]
there need to be mechanism to trigger it back, how you will change db when you got installed shoko ? removing programdata (windows) ? What more non-user friendly you want to do it ? ;-)

**Comment by hidden4003** [comment]
you are not supposed to change DB, we have no migration tools and everyone who tried to migrate ran into issues, so it is more of a troubleshooting step in case your server does not start up.

I really don't see how this is a setting.

**Comment by bigretromike** [comment]
its not about migrate, its more about to start fresh without needing to manually remove settings.json

**Comment by ElementalCrisis** [comment]
All you would need to do is delete the .db3 file then. All the other settings can be changed in either the Web UI or Desktop.

**Comment by bigretromike** [comment]
Why db3 ? Do we store settings in db now ?:-) 

On April 2, 2018 1:35:46 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>All you would need to do is delete the .db3 file then. All the other
>settings can be changed in either the Web UI or Desktop. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer-WebUI/issues/70#issuecomment-377912084

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hidden4003** [comment]
@bigretromike I don't think we store settings in DB, settings are stored in settings.json and before that in app config, i.e. ShokoServer.exe.config next to exe.

**Comment by bigretromike** [comment]
I know @hidden4003 but what the f.. is @ElementalCrisis talking about then? why I would want to delete .db3 (sqlite db) to wipe my db settings and set them again ?! 
I see that we didn't understand each other ...

**Comment by ElementalCrisis** [comment]
Ah yeah I thought you were referring to your collection. I

Regardless, if a user wants to start fresh then they will have to delete settings,json. I don't want there to be a button to accidentally wipe your settings.

**Comment by bigretromike** [comment]
You just add 1 or 2 dialog boxes with yes/no with red text and that its. All system with webui got that... Also its already in server ui, so whats the problem ?

**Comment by ElementalCrisis** [comment]
There is no button in current Server UI to wipe your settings. You can change which you can currently do in Web UI.

**Comment by bigretromike** [comment]
there is to change db which is essentially wipe command (as @hidden4003 stated that migration is fail here);
if its so problematic to make this in webui then its easier and give similar results to add "wipe"

**Comment by ElementalCrisis** [comment]
That doesn't wipe your settings.json file, it just adds the new DB info to it. Like I said before I believe we don't need one as it serves no purpose.

Also you can change DB without any repercussions, I do it all the time. We've never supported migration from one DB type to another which is what @hidden4003 was referring to.

**Comment by bigretromike** [comment]
@ElementalCrisis no, he was reffering to channging db settings as its 'legacy' and wont add it.

**Comment by ElementalCrisis** [comment]
MySQL and SQL Server are no longer being offered as DB options and SQLite doesn't have any DB options. For users currently using MySQL and SQL Server they are going to have to manually edit the settings.json file to make changes if needed.

**Comment by bigretromike** [comment]
oh, thats something new. mkay

**Comment by bigretromike** [comment]
I total agree with you @hidden4003 
I don't mind sqlite at all.

**Comment by hidden4003** [comment]
Most of the settings done so I think we release 0.3.4 together with upcoming server release.
