### ISSUE TITLE
Log User out if Shoko Detects Username or Password Change

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#80]
Currently the user stays logged in with a **401: Unauthorized** message being shown. Instead if the user account is updated outside of the Web UI, the user should be logged out. 

Also it seems to have caused another bug as I can log in with the new username but still get the **401: Unauthorized** message.

**Comment by bigretromike** [comment]
its somehow wrong.
We dont use user name and password with webui we use them to get apikey, and until apikey is revoked it wont change even if you change password - What would be the point? Only way to do it is implement a regeneration function on server side that will trigger apikey regeneration on password change. Interested ?

**Comment by ElementalCrisis** [comment]
APIKey is fine, I just can't use  the Web UI now because i changed my username.

**Comment by bigretromike** [comment]
you had right about apikey should change. if your apikey is compromised you should be able to quickly revoke them via changing password.

**Comment by bigretromike** [comment]
@ElementalCrisis fell free to add proper option while changing password to check/uncheck ability to revoke apikeys. Default behavior is to revoke them

**Comment by ElementalCrisis** [comment]
Awesome, you rock @bigretromike! :)

**Comment by hidden4003** [comment]
@bigretromike is 401 code unique in the way that it is only generated if api key is invalid? Then I can use it to wipe the key and it will automatically redirect user to login, as it is how logout works.

**Comment by bigretromike** [comment]
401 is unathorizated access, if you dont have correct apikey you get 401 allways. I do rember da3dsoul pit one 401 somewhere but yeah, its unique for authorization
