### ISSUE TITLE
Updated Dashboard

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer-WebUI#86]
![dashboard - updated](https://cloud.githubusercontent.com/assets/9443295/22402368/ab6633de-e5a9-11e6-8be2-ef0090d28f19.png)

I changed some things in the top toolbar, expanded the user drop-down to include the username and their avatar as well as show the options available when clicking the arrow. I also added an number indicator to the global notifications. On the right I added an example of what the expanded queues should look like when they are clicked. 

I also added a search button that allows the user to search. For example, what if the user wanted to quickly check if they have Series X or what fansub group?

**Comment by bigretromike** [comment]
Image? As it look nice and generic, what would be the point ? maybe instead of login name ...

**Comment by ElementalCrisis** [comment]
Because it makes it inline with ClientV2.

**Comment by bigretromike** [comment]
still if the image would be there then throw out usename as its duplicate functionality also username can introduce security an css issues when very long without spaces.

**Comment by ElementalCrisis** [comment]
If the username is over X characters we trim it.

**Comment by bigretromike** [comment]
still the point is the image and username make it duplicated...

**Comment by bigretromike** [comment]
see github ? it have only image.. because why waste space for same information

**Comment by ElementalCrisis** [comment]
Right, so we go with what I said in the second part of my reply, user avatar that's clickable.

**Comment by bigretromike** [comment]
> user drop-down to include the username and their avatar as well
right ;-)

**Comment by hidden4003** [comment]
Regarding the dropdown, if I just push the items I get from polling there will be a lot of stuff missing as server processes items way faster than once in 4 sec. (current poll interval).

I see two possible solutions:

- websockets, that way I don't need to poll and server sends me all the events
- server keeps a list of past xx commands and their status and I get new api call to get the list

**Comment by ElementalCrisis** [comment]
I vote for websockets. 

They can also be used in ClientV2 and to be honest we were already planning for realtime data so they would be needed anyways.

**Comment by bigretromike** [comment]
so we can wipe out anything webui related from api, as you will use websockets anyway.

**Comment by bigretromike** [comment]
also @ElementalCrisis fell free to use github to reach me.

**Comment by hidden4003** [comment]
@bigretromike websockets only viable for real-time stuff like notifications or queue status updates, not really viable for API requests as then another layer between websockets and api would be needed, why maintain two?

**Comment by bigretromike** [comment]
I dunno why maintain both, so basicly you want request apo for information then connect to socket and wait for notification about changes, and then what you get data from socket not api, so why bother with quering api? If im wrong please correct me

**Comment by bigretromike** [comment]
Or apiparameter for time and only send items after that time? Dunno. If you think webspckets are the thing to go fell free to implemnet them

**Comment by hidden4003** [comment]
There are a lot of benefits for other clients as well as websocket allows to get rid of any sort of polling. Your solution with change tracking is major change for server architecture in general. I will look into implementing it myself then.

**Comment by bigretromike** [comment]
solution with `time` isn't major change in architecture imo.
I understand that you want websockets as it was topic before but end up with discarding the idea at the end. But if you are able to create websocket support that will work in cross-compatible envirement go ahead if you think that anyone except webui and ?clientv2? would benefit from it them you have green light.

**Comment by hidden4003** [comment]
Dashboard is new now and will be changed further.
